version: '3.4'

services:
  crawler.api:
    image: ${DOCKER_REGISTRY-}crawlerapi
    container_name: crawler-api
    build:
      context: .
      dockerfile: Crawler.API/Dockerfile
    networks:
      - data-network
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - data-network

networks:
  data-network:  
    driver: bridge